name = "sentinel-auth-api"
main = "src/index.ts"
compatibility_date = "2026-04-26"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
MONGO_DATABASE = "sentinel_ai"

[observability]
enabled = true
